---
- hosts: all
  vars:
    packages: [git,vim,ruby]
  tasks:
  - name: install packages for Debian style OSs
    apt:
      name: '{{item}}'
      state: '{{pkg_state}}'
    with_items: '{{packages}}'
    when: ansible_os_family == 'Debian'

  - name: install packages for Redhat style OSs
    yum:
      name: '{{item}}'
      state: '{{pkg_state}}'
    with_items: '{{packages}}'
    when: ansible_os_family == 'Debian'

  - name: create file based on packages names
    file:
      dest: /tmp/{{item}}
      state: '{{file_state}}'
    with_items: '{{packages}}'
    when: ansible_os_family == 'Debian'
